# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

linear_sim_embed_cpp <- function(X, T, M, sigma_P, ncomp, alpha_p, maxit = 200L, tol = 1e-8, batch_size = 1) {
    .Call('_musca_linear_sim_embed_cpp', PACKAGE = 'musca', X, T, M, sigma_P, ncomp, alpha_p, maxit, tol, batch_size)
}

